-- Initial schema (DAT-01 to DAT-08).
-- Money is NUMERIC(12,2); negative = money out, positive = money in.
-- Constraints and indexes are named explicitly so errors and tests can refer to them.

CREATE EXTENSION IF NOT EXISTS vector;

-- DAT-01 ---------------------------------------------------------------------

CREATE TABLE account (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name        TEXT        NOT NULL,
    institution TEXT        NOT NULL,
    type        TEXT        NOT NULL,
    last_four   CHAR(4)     NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_account PRIMARY KEY (id),
    CONSTRAINT ck_account_type CHECK (type IN ('CHECKING', 'SAVINGS', 'CREDIT_CARD')),
    CONSTRAINT ck_account_last_four CHECK (last_four ~ '^[0-9]{4}$')
);

COMMENT ON TABLE account IS
    'A user account. Only the last four digits are stored; full account numbers are never stored.';

-- Statements -----------------------------------------------------------------

CREATE TABLE statement (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account_id       BIGINT        NOT NULL,
    period_start     DATE          NOT NULL,
    period_end       DATE          NOT NULL,
    opening_balance  NUMERIC(12,2),
    closing_balance  NUMERIC(12,2),
    status           TEXT          NOT NULL DEFAULT 'IMPORTED',
    source_file_name TEXT          NOT NULL,
    file_hash        TEXT          NOT NULL,
    section_totals   JSONB         NOT NULL DEFAULT '{}',
    imported_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT pk_statement PRIMARY KEY (id),
    CONSTRAINT fk_statement_account FOREIGN KEY (account_id) REFERENCES account (id),
    CONSTRAINT ck_statement_status CHECK (status IN ('IMPORTED', 'NEEDS_REVIEW', 'RECONCILED')),
    CONSTRAINT ck_statement_period CHECK (period_end >= period_start),
    CONSTRAINT ck_statement_section_totals_object CHECK (jsonb_typeof(section_totals) = 'object'),
    CONSTRAINT uq_statement_file_hash UNIQUE (file_hash),
    CONSTRAINT uq_statement_account_period UNIQUE (account_id, period_start, period_end),
    -- Target of txn's composite FK, so a txn's account always matches its statement's account.
    CONSTRAINT uq_statement_id_account UNIQUE (id, account_id)
);

COMMENT ON COLUMN statement.section_totals IS
    'Totals as printed on the statement, keyed by source_section, e.g. {"DEPOSIT": 2500.00, "FEE": -12.50}. '
    'Used to reconcile the imported rows of each section against the printed total.';

-- DAT-02 ---------------------------------------------------------------------

CREATE TABLE category (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name      TEXT   NOT NULL,
    kind      TEXT   NOT NULL,
    parent_id BIGINT,
    CONSTRAINT pk_category PRIMARY KEY (id),
    CONSTRAINT uq_category_name UNIQUE (name),
    CONSTRAINT ck_category_kind CHECK (kind IN ('EXPENSE', 'INCOME', 'TRANSFER')),
    CONSTRAINT fk_category_parent FOREIGN KEY (parent_id) REFERENCES category (id),
    CONSTRAINT ck_category_not_own_parent CHECK (parent_id <> id)
);

-- DAT-03 to DAT-05, DAT-07, DAT-08 -------------------------------------------

CREATE TABLE txn (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    account_id         BIGINT        NOT NULL,
    statement_id       BIGINT        NOT NULL,
    txn_date           DATE          NOT NULL,
    post_date          DATE,
    raw_description    TEXT          NOT NULL,
    merchant           TEXT,
    amount             NUMERIC(12,2) NOT NULL,
    source_section     TEXT          NOT NULL,
    check_number       VARCHAR(20),
    counterparty       TEXT,
    category_id        BIGINT,
    category_source    TEXT,
    is_transfer        BOOLEAN       NOT NULL DEFAULT false,
    fingerprint        TEXT          NOT NULL,
    source_line_number INT,
    source_line_text   TEXT,
    created_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT pk_txn PRIMARY KEY (id),
    CONSTRAINT fk_txn_account FOREIGN KEY (account_id) REFERENCES account (id),
    CONSTRAINT fk_txn_statement_account FOREIGN KEY (statement_id, account_id)
        REFERENCES statement (id, account_id) ON DELETE CASCADE,
    CONSTRAINT fk_txn_category FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE SET NULL,
    CONSTRAINT ck_txn_source_section CHECK (source_section IN
        ('DEPOSIT', 'WITHDRAWAL', 'CHECK', 'FEE', 'PAYMENT', 'PURCHASE', 'INTEREST', 'OTHER')),
    CONSTRAINT ck_txn_category_source CHECK (category_source IN ('RULE', 'AI', 'USER')),
    -- A category is never set without recording who set it, and vice versa.
    CONSTRAINT ck_txn_category_has_source CHECK ((category_id IS NULL) = (category_source IS NULL)),
    CONSTRAINT ck_txn_source_line_number CHECK (source_line_number > 0),
    CONSTRAINT uq_txn_fingerprint UNIQUE (fingerprint)
);

CREATE INDEX ix_txn_account_date ON txn (account_id, txn_date);
CREATE INDEX ix_txn_category ON txn (category_id);
CREATE INDEX ix_txn_transfer_date ON txn (is_transfer, txn_date);
CREATE INDEX ix_txn_statement_section ON txn (statement_id, source_section);

COMMENT ON COLUMN txn.txn_date IS
    'When the purchase happened. Taken from a date embedded in the description when present '
    '(e.g. "CHECKCARD 0704 ..."), otherwise the posting date.';
COMMENT ON COLUMN txn.post_date IS
    'The date printed in the statement''s date column. Null when the statement prints only one date.';
COMMENT ON COLUMN txn.raw_description IS
    'Full original description with wrapped lines joined. Never modified.';
COMMENT ON COLUMN txn.amount IS
    'Negative = money out, positive = money in. Zero is allowed (fee waivers, rebate notes).';
COMMENT ON COLUMN txn.source_section IS
    'Statement section the row came from. PAYMENT, PURCHASE and INTEREST are for credit card statements. '
    'Rows are summed per section to reconcile against statement.section_totals.';
COMMENT ON COLUMN txn.counterparty IS
    'Person-to-person payee or payer (e.g. Zelle). LOCAL ONLY: must never be sent to a cloud model.';

-- DAT-05 ---------------------------------------------------------------------

CREATE TABLE categorization_rule (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    pattern     TEXT        NOT NULL,
    match_type  TEXT        NOT NULL,
    category_id BIGINT      NOT NULL,
    source      TEXT        NOT NULL,
    priority    INT         NOT NULL DEFAULT 0,
    active      BOOLEAN     NOT NULL DEFAULT true,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_categorization_rule PRIMARY KEY (id),
    CONSTRAINT fk_categorization_rule_category FOREIGN KEY (category_id) REFERENCES category (id),
    CONSTRAINT ck_categorization_rule_match_type CHECK (match_type IN ('CONTAINS', 'REGEX')),
    CONSTRAINT ck_categorization_rule_source CHECK (source IN ('SEED', 'USER_CORRECTION'))
);

CREATE INDEX ix_categorization_rule_category ON categorization_rule (category_id);

-- Transfers (GR-04) ----------------------------------------------------------

CREATE TABLE transfer_link (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    out_txn_id BIGINT      NOT NULL,
    -- Nullable so a card payment can be marked as a transfer before the card's statement is imported.
    in_txn_id  BIGINT,
    method     TEXT        NOT NULL,
    status     TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_transfer_link PRIMARY KEY (id),
    CONSTRAINT fk_transfer_link_out FOREIGN KEY (out_txn_id) REFERENCES txn (id) ON DELETE CASCADE,
    CONSTRAINT fk_transfer_link_in FOREIGN KEY (in_txn_id) REFERENCES txn (id) ON DELETE CASCADE,
    CONSTRAINT uq_transfer_link_out UNIQUE (out_txn_id),
    CONSTRAINT uq_transfer_link_in UNIQUE (in_txn_id),
    CONSTRAINT ck_transfer_link_distinct CHECK (out_txn_id <> in_txn_id),
    CONSTRAINT ck_transfer_link_method CHECK (method IN ('AUTO', 'USER')),
    CONSTRAINT ck_transfer_link_status CHECK (status IN ('MATCHED', 'UNMATCHED')),
    CONSTRAINT ck_transfer_link_status_matches_in CHECK ((status = 'MATCHED') = (in_txn_id IS NOT NULL))
);

-- DAT-06 ---------------------------------------------------------------------

CREATE TABLE merchant_embedding (
    merchant   TEXT         NOT NULL,
    embedding  vector(1024) NOT NULL,
    model      TEXT         NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_merchant_embedding PRIMARY KEY (merchant)
);

CREATE INDEX ix_merchant_embedding_hnsw ON merchant_embedding USING hnsw (embedding vector_cosine_ops);
